version: 2
updates:
  # Keep Rust dependencies up to date
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "rust"
    
  # Keep LSP server Rust dependencies up to date
  - package-ecosystem: "cargo"
    directory: "/lsp-server"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "rust"
      - "lsp-server"
  
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"