id = "phpmd"
name = "PHPMD"
version = "0.1.0"
schema_version = 1
authors = ["Mike Bronner <mike@genealabs.com>"]
description = "PHP Mess Detector Language Server for analyzing PHP code complexity and potential problems. Detects code smells, possible bugs, suboptimal code, and unused parameters/methods/properties."
repository = "https://github.com/GeneaLabs/zed-phpmd-lsp"

[lib]
kind = "Rust"
version = "0.1.0"

[language_servers.phpmd]
name = "PHPMD"
languages = ["PHP"]
language_ids = { PHP = "php" }
settings = { ruleset = "cleancode,codesize,controversial,design,naming,unusedcode" }