id = "phpmd"
name = "PHPMD"
version = "0.1.0"
schema_version = 1
authors = ["Mike Bronner <mike@genealabs.com>"]
description = "PHP Mess Detector Language Server for linting PHP code. We are looking for feedback, especially for Windows and Linux platforms."
repository = "https://github.com/GeneaLabs/zed-phpmd-lsp"

[lib]
kind = "Rust"
version = "0.1.0"

[language_servers.phpmd]
name = "PHPMD"
languages = ["PHP"]
language_ids = { PHP = "php" }
settings = { rulesets = "cleancode,codesize,controversial,design,naming,unusedcode" }
