title: "Bug Report: "
labels: ["bug-report", "needs-investigation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! This helps us improve the extension for everyone.
        
        **Note:** If this turns out to be a confirmed bug, we'll escalate it to an issue for tracking.

  - type: input
    id: zed-version
    attributes:
      label: "Zed Version"
      description: "What version of Zed are you using?"
      placeholder: "e.g., 0.120.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "Operating System"
      description: "What OS are you running?"
      placeholder: "e.g., macOS 14.0, Ubuntu 22.04, Windows 11"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "Describe the bug in detail"
      placeholder: "Extension doesn't highlight violations, crashes on startup, etc."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "What did you expect to happen?"
      description: "What should have happened instead?"
      placeholder: "Expected to see red underlines for PSR-12 violations"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce"
      description: "How can we reproduce this issue?"
      placeholder: |
        1. Open Zed
        2. Create a new PHP file
        3. Type some code that violates PSR-12
        4. ...
    validations:
      required: true

  - type: textarea
    id: php-code
    attributes:
      label: "Sample PHP code (if relevant)"
      description: "Share the PHP code that's causing issues"
      render: php
      placeholder: |
        <?php
        // Your PHP code here
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: "Configuration"
      description: "Share your Zed settings or phpcs.xml if relevant"
      render: json
      placeholder: |
        {
          "lsp": {
            "phpcs-lsp-server": {
              "settings": {
                "standard": "PSR12"
              }
            }
          }
        }
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Debug logs"
      description: "Any error messages from Zed's debug console?"
      render: text
      placeholder: "Check Zed → View → Debug Console for error messages"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-submission checklist"
      options:
        - label: "I've searched existing discussions and issues for this problem"
          required: true
        - label: "I've restarted Zed to see if that fixes the issue"
          required: true
        - label: "I've provided clear steps to reproduce the issue"
          required: true